### ISSUE TITLE
Tiva 123GXL UART Setup

### ISSUE THREAD

**Issue by akshita-bhasin** [cu-ecen-5013/final-project-akshita-bhasin#2]
**DoD**
Set up UART Communication on Tiva, and test a basic UART code.

Status of DoD : Verified, as evident from the screenshots below

**Comment by madhukararora** [comment]
Faced issues in working with UART Module 2 and UART Module 3, tried different modules from the 8 available on the development board. 

Finally settled on using Module 1 and Module 3.
Able to do a loop-back UART Test on the TIVA Board using UART in polling mode. 
![LoopBack_1](https://user-images.githubusercontent.com/55379299/79083694-133bc900-7ced-11ea-8206-c1a4c0fdd78f.PNG)


As seen from the screenshot, there were garbage values when working with polling mode. Use main.c to verify.
[Link to commit version of UART working in Polling Mode](https://github.com/cu-ecen-5013/s20-environmental-monitoring-tiva/tree/49c86711a1bc96623a9221eacf143f40d1502c8e)

**Comment by madhukararora** [comment]
Interrupt Based UART Loop-Back setup successfully.
Repeatedly transferring the "Hello,World!" string. No garbage data received. 
![LoopBack_2](https://user-images.githubusercontent.com/55379299/79090732-e3e68580-7d07-11ea-9f0d-e9b0305acdde.PNG)

[Link to commit version of UART working in Interrupt Mode](https://github.com/cu-ecen-5013/s20-environmental-monitoring-tiva/tree/f3b91dcba5a6642d4d09e9fd6c534757da2fd79c)
