### ISSUE TITLE
FreeRTOS Environment Setup

### ISSUE THREAD

**Issue by akshita-bhasin** [cu-ecen-5013/final-project-akshita-bhasin#4]
**DoD**
Set-up FreeRTOS on Tiva TM4C123GXL.

Status of DoD : Verified, as evident from the screenshots below.

**Comment by madhukararora** [comment]
Referring to https://github.com/cu-ecen-5013/tiva-freertos-setup-example

**Comment by madhukararora** [comment]
![FreeRTOS - Setup](https://user-images.githubusercontent.com/55379299/79092531-6d00bb00-7d0e-11ea-9cbd-7bd94cfe8604.PNG)
Set-up FreeRTOS Demo project, and tested LED blinking on Tiva.

[Link to FreeRTOS - Setup Commit Version](https://github.com/cu-ecen-5013/s20-environmental-monitoring-tiva/tree/a41d8a018ae575f54a577791fddaaca895d9a237)
