### ISSUE TITLE
Implement I2C driver BBB

### ISSUE THREAD

**Issue by akshita-bhasin** [cu-ecen-5013/final-project-akshita-bhasin#5]
Write a driver on buildroot for the BBB to perform I2C operations.

**DoD**: I2C working and verified using logic analyzer

**Comment by jajoosiddhant** [comment]
@akshita-bhasin 
Will this be an I2C kernel driver from scratch or a user space driver using buildroot I2C package?

**Comment by akshita-bhasin** [comment]
I have been trying to do a user space driver, but have been facing issues getting enough material on how to work with I2C patches. For the Linux I2C driver it works, but not with my custom driver. Been looking for some material on it.

**Comment by akshita-bhasin** [comment]
Using linux I2C driver for TMP102, and [#1](https://github.com/cu-ecen-5013/s20-environmental-monitoring-tiva/issues/1) designing a user space driver using buildroot I2C package.

**Status**: Issue dropped
